# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'load_srt_UI.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class UiLoadSrt(object):
    def setupUi(self, load_srt):
        load_srt.setObjectName("load_srt")
        load_srt.resize(600, 197)
        load_srt.setMinimumSize(QtCore.QSize(0, 10))
        load_srt.setMaximumSize(QtCore.QSize(16777215, 197))
        self.gridLayout = QtWidgets.QGridLayout(load_srt)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(load_srt)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.import_box = QtWidgets.QGroupBox(self.tab)
        self.import_box.setTitle("")
        self.import_box.setObjectName("import_box")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.import_box)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.file_lbl = QtWidgets.QLabel(self.import_box)
        self.file_lbl.setObjectName("file_lbl")
        self.gridLayout_3.addWidget(self.file_lbl, 0, 0, 1, 1)
        self.select_file_btn = QtWidgets.QPushButton(self.import_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_file_btn.sizePolicy().hasHeightForWidth())
        self.select_file_btn.setSizePolicy(sizePolicy)
        self.select_file_btn.setObjectName("select_file_btn")
        self.gridLayout_3.addWidget(self.select_file_btn, 0, 1, 1, 1)
        self.load_btn = QtWidgets.QPushButton(self.import_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.load_btn.sizePolicy().hasHeightForWidth())
        self.load_btn.setSizePolicy(sizePolicy)
        self.load_btn.setObjectName("load_btn")
        self.gridLayout_3.addWidget(self.load_btn, 1, 0, 1, 2)
        self.progressBar = QtWidgets.QProgressBar(self.import_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_3.addWidget(self.progressBar, 2, 0, 1, 2)
        self.gridLayout_2.addWidget(self.import_box, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.config_box = QtWidgets.QGroupBox(self.tab_2)
        self.config_box.setTitle("")
        self.config_box.setObjectName("config_box")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.config_box)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.db_file_label = QtWidgets.QLabel(self.config_box)
        self.db_file_label.setMaximumSize(QtCore.QSize(250, 16777215))
        self.db_file_label.setObjectName("db_file_label")
        self.gridLayout_4.addWidget(self.db_file_label, 0, 0, 1, 1)
        self.select_file_btn_2 = QtWidgets.QPushButton(self.config_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.select_file_btn_2.sizePolicy().hasHeightForWidth())
        self.select_file_btn_2.setSizePolicy(sizePolicy)
        self.select_file_btn_2.setMaximumSize(QtCore.QSize(250, 16777215))
        self.select_file_btn_2.setObjectName("select_file_btn_2")
        self.gridLayout_4.addWidget(self.select_file_btn_2, 0, 1, 1, 1)
        self.word_scoring_lbl = QtWidgets.QLabel(self.config_box)
        self.word_scoring_lbl.setMaximumSize(QtCore.QSize(250, 16777215))
        self.word_scoring_lbl.setObjectName("word_scoring_lbl")
        self.gridLayout_4.addWidget(self.word_scoring_lbl, 1, 0, 1, 1)
        self.word_scoring_combo = QtWidgets.QComboBox(self.config_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_scoring_combo.sizePolicy().hasHeightForWidth())
        self.word_scoring_combo.setSizePolicy(sizePolicy)
        self.word_scoring_combo.setObjectName("word_scoring_combo")
        self.word_scoring_combo.addItem("")
        self.gridLayout_4.addWidget(self.word_scoring_combo, 1, 1, 1, 1)
        self.word_lemma_lbl = QtWidgets.QLabel(self.config_box)
        self.word_lemma_lbl.setMaximumSize(QtCore.QSize(250, 16777215))
        self.word_lemma_lbl.setObjectName("word_lemma_lbl")
        self.gridLayout_4.addWidget(self.word_lemma_lbl, 2, 0, 1, 1)
        self.word_lemma_combo = QtWidgets.QComboBox(self.config_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_lemma_combo.sizePolicy().hasHeightForWidth())
        self.word_lemma_combo.setSizePolicy(sizePolicy)
        self.word_lemma_combo.setObjectName("word_lemma_combo")
        self.word_lemma_combo.addItem("")
        self.word_lemma_combo.addItem("")
        self.word_lemma_combo.addItem("")
        self.gridLayout_4.addWidget(self.word_lemma_combo, 2, 1, 1, 1)
        self.word_trans_lbl = QtWidgets.QLabel(self.config_box)
        self.word_trans_lbl.setObjectName("word_trans_lbl")
        self.gridLayout_4.addWidget(self.word_trans_lbl, 3, 0, 1, 1)
        self.word_trans_combo = QtWidgets.QComboBox(self.config_box)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.word_trans_combo.sizePolicy().hasHeightForWidth())
        self.word_trans_combo.setSizePolicy(sizePolicy)
        self.word_trans_combo.setObjectName("word_trans_combo")
        self.word_trans_combo.addItem("")
        self.gridLayout_4.addWidget(self.word_trans_combo, 3, 1, 1, 1)
        self.gridLayout_5.addWidget(self.config_box, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(load_srt)
        self.tabWidget.setCurrentIndex(1)
        self.select_file_btn.clicked.connect(load_srt.open_file_dialog)
        self.load_btn.clicked.connect(load_srt.load_file_action)
        self.select_file_btn_2.clicked.connect(load_srt.open_database_file)
        self.word_scoring_combo.currentIndexChanged['QString'].connect(load_srt.API_settings_changed)
        self.word_lemma_combo.currentIndexChanged['QString'].connect(load_srt.API_settings_changed)
        self.word_trans_combo.currentIndexChanged['QString'].connect(load_srt.API_settings_changed)
        QtCore.QMetaObject.connectSlotsByName(load_srt)

    def retranslateUi(self, load_srt):
        _translate = QtCore.QCoreApplication.translate
        load_srt.setWindowTitle(_translate("load_srt", "Load srt file"))
        self.file_lbl.setText(_translate("load_srt", "File: "))
        self.select_file_btn.setText(_translate("load_srt", "Select file"))
        self.load_btn.setText(_translate("load_srt", "Load"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("load_srt", "Import"))
        self.db_file_label.setText(_translate("load_srt", "Database file:"))
        self.select_file_btn_2.setText(_translate("load_srt", "Select File"))
        self.word_scoring_lbl.setText(_translate("load_srt", "Word scoring engine"))
        self.word_scoring_combo.setItemText(0, _translate("load_srt", "TwinWordAPI"))
        self.word_lemma_lbl.setText(_translate("load_srt", "Word lemmatization engine"))
        self.word_lemma_combo.setItemText(0, _translate("load_srt", "WiktionaryAPI"))
        self.word_lemma_combo.setItemText(1, _translate("load_srt", "UltraLinguaAPI"))
        self.word_lemma_combo.setItemText(2, _translate("load_srt", "LinguaRobotAPI"))
        self.word_trans_lbl.setText(_translate("load_srt", "Word translation engine"))
        self.word_trans_combo.setItemText(0, _translate("load_srt", "Offline Database"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("load_srt", "Config"))


